# .github/workflows/ci.yml
name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Set up JDK 11 and automatically cache Maven dependencies
      - name: Set up JDK 11 & cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      # 3. Build & run tests
      - name: Build with Maven
        run: mvn --batch-mode clean test
